### PR TITLE
Created a provider for Catalyze

### PR DESCRIPTION
**Pull request by meirgottlieb**
I created a dpl provider for [Catalyze](https://catalyze.io/). I can't give you a link to an example build since since it is a private repository but I have tested it and it works.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Hello, there!

Could you add specs, please?

**Comment by jault3** [comment]
Hello, I just wanted to chime in on this and give a quick comment as I work for Catalyze. The only change I would suggest @meirgottlieb, is removing the `--quiet` flags from the git pushes. There's lots of useful build output helpful in debugging when a push is performed that may otherwise be missed with the `--quiet` flag. Otherwise from a Catalyze perspective, it looks great!

**Comment by meirgottlieb** [comment]
Hey @jault3, thanks for reviewing this. I've removed the `--quiet` flag.

**Comment by meirgottlieb** [comment]
@jault3, one more thing - did you have a chance to review the setup documentation [here](https://github.com/meirgottlieb/dpl/tree/catalyze_provider#catalyze)?

**Comment by jault3** [comment]
I did, the CLI commands and the known_hosts addition are correct. Going forward, we will try and post our public SSH keys to so that they can be copied.

**Comment by meirgottlieb** [comment]
Great. Thank you.

**Comment by BanzaiMan** [comment]
Sorry for the delay.

Could you update the PR, and test it one more time and link to the build URL?

Thanks.

**Comment by meirgottlieb** [comment]
PR is current with master. Here is the build [url](https://travis-ci.com/artifacthealth/artifact/builds/27337706).

**Comment by BanzaiMan** [comment]
@meirgottlieb Could you also documentation to https://github.com/travis-ci/docs-travis-ci-com as well? Thank you!

**Comment by meirgottlieb** [comment]
@jault3 did you ever post the Catalyze public SSH keys anywhere?

**Pull request merged**
