### PR TITLE
Fixed deployment error on Xenial when target branch does not exist in the remote repo.

### PR DESCRIPTION
**Pull request by biodranik**
The error can be seen here: https://travis-ci.org/biodranik/files.alex.bio/builds/504537003

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Thanks for the PR.

I think `FileUtils`' `FileUtils.mkdir_p` makes the intent clearer.

**Comment by biodranik** [comment]
Thanks, @BanzaiMan, I've used FileUtils as you mentioned.

**Comment by BanzaiMan** [comment]
Thanks! Do you have a test deployment?

**Comment by biodranik** [comment]
No, I don't have it.

**Comment by BanzaiMan** [comment]
Please test it.

**Comment by biodranik** [comment]
I'm not familiar with Ruby and don't have a Linux system, any ideas about how it should be done? Can anyone from your team help?

**Comment by BanzaiMan** [comment]
This is described in https://github.com/travis-ci/dpl/blob/master/.github/CONTRIBUTING.md#testing-dpl-in-the-context-of-travis-ci-builds

**Comment by biodranik** [comment]
@BanzaiMan Thanks for all the hints, I have finally tested my change in my repo, and it works on xenial, as suspected. Here is the link to a successful build with my proposed fix: https://travis-ci.org/biodranik/files.alex.bio/builds/511327884

Please note, that this PR checks failed because of the error in some other provider, not GitHub pages which I fixed.

**Comment by BanzaiMan** [comment]
This should be implemented in v2 now.

Please try:

```yaml
deploy:
  provider: pages
  edge:
    branch: master
⋮
```

**Comment by biodranik** [comment]
What is v2? The request is not merged yet.

**Comment by BanzaiMan** [comment]
v2 is a rewrite we are working on, and this PR has been incorporated into it.

**Comment by biodranik** [comment]
Great! Is it’s code publicly available?

**Comment by BanzaiMan** [comment]
Yes! See https://github.com/travis-ci/dpl/pull/966#issuecomment-520557419.

**Comment by JounQin** [comment]
@BanzaiMan Seems not working to me.
https://travis-ci.com/mjolnirjs/stated-bean/jobs/225405279#L431

**Comment by svenfuchs** [comment]
@JounQin the log output looks a little funny, but it seems to say that the deployment has happened. 

if it didn't, could you please open a new ticket, mentioning `v2` and the link to your build?

i am going to close this PR here because the original issue has been addressed by using a different strategy in the `pages` provider in `v2`. we now check if the branch exists, and only then `git clone` it, otherwise `git init` https://github.com/travis-ci/dpl/blob/master/lib/dpl/providers/pages.rb#L87. please feel free to re-open it.

**Comment by JounQin** [comment]
@svenfuchs I manually pushed `gh-pages` branch and restarted the build, so the error logs are missing...

**Comment by svenfuchs** [comment]
@JounQin ok, i am going to try to reproduce this, and open a new ticket if i can. thanks!

**Comment by svenfuchs** [comment]
follow-up ticket here: https://github.com/travis-ci/dpl/issues/1054

**Pull request closed without merging**
