### PR TITLE
Lambda java handler

### PR DESCRIPTION
**Pull request by couryrr**
This is to address the issue described here https://travis-ci.community/t/java-aws-handler-separator-is-incorrect/4116/2 as well as other runtime requirements.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
The failure is coming from https://github.com/travis-ci/dpl/commit/6f49b25d174d1baf01970ee4533125f016996cad.

**Comment by couryrr** [comment]
I am going to put a change in this for the default timeout and memory.

**Comment by svenfuchs** [comment]
@couryrr We have a major new version of dpl in the works, that we would want to port your changes to https://github.com/travis-ci/dpl/blob/dpl-2/lib/dpl/providers/lambda.rb (depending on the urgency of this it even might make sense to target dpl v2 only).

I would be happy to do the work of porting your changes, but I might need some help with testing it. In fact, I am still looking for someone familiar with AWS Lambda, who can help/guide me implementing [a simple integration test](https://github.com/travis-ci/dpl/blob/dpl-2/CONTRIBUTING_2.md), too. 

Would it be alright for me to get in touch with you about this via your email address on your GitHub profile?

**Comment by couryrr** [comment]
@svenfuchs absolutely I am more then happy to help where I can.

**Comment by svenfuchs** [comment]
@couryrr Thanks for this PR! I have ported the logic to https://github.com/travis-ci/dpl/pull/1076, now targeting `master` (dpl v2).

Since you are the original author of this, would you like me to amend my commit with your Git author name? I'd be happy to pass authorship, but also did not want to assume. Please let me know.

I am going to close this PR here.

**Pull request closed without merging**
