### PR TITLE
[GitHub Pages] Support setting local-dir to an absolute path

### LINKED ISSUE #753: Allow absolute path to be used in GitHub Pages deployment
I'd like the `local-dir` option to support absolute paths in addition to relative paths. If this sounds reasonable, I'd be happy to open a PR.

### PR DESCRIPTION
**Pull request by brianhou**
@webknjaz 

This PR resolves #753. Here's a successful build: https://travis-ci.org/brianhou/dpl-test/builds/343625965

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Hello, there. Sorry for the delay. I'm reorganizing code for the 1.9.0 release, so PRs are on hold until I can get that out of the way. Deployment provide code should not be affected, but I do not plan to have another release before 1.9.0.

Thank you for your understanding.

**Comment by BanzaiMan** [comment]
Please test again. Thanks.

**Comment by BanzaiMan** [comment]
Also, test with a relative path, and add specs, please.

**Comment by brianhou** [comment]
Here are a couple tests with an absolute path and a relative path: https://travis-ci.org/brianhou/dpl-test/builds/343625965, https://travis-ci.org/brianhou/dpl-test/builds/351790053.

Can you clarify what you mean by adding specs? I'm not particularly familiar with Ruby development.

**Comment by BanzaiMan** [comment]
I now realize that the Pages provider doesn't have any spec.

**Comment by webknjaz** [comment]
Unfortunately I didn't have time to learn how to create specs :( I'd like to though. Still somewhere on my list, but I'm too busy to jump into it right now. I've tried to start doing specs several time, but stuck with a framework.
If someone is willing to help with this, I'll be glad to be reviewing/collaborating on tests.

**Comment by webknjaz** [comment]
btw @brianhou it's possible to have a list of providers in deploy step, so that you don't have to test different modes in separate commits. Also this is kinda smoke test helping to detect if subsequent provider runs don't influence/break each other.

```yaml
deploy:
- &_base_provider
  provider: pages
  github-token: $GITHUB_TOKEN
  edge:
    source: brianhou/dpl
    branch: master
  on:
    branch: master
  skip-cleanup: true
  local-dir: gh-pages
  keep-history: false
  verbose: true
# second run with overridden args:
- <<: *_base_provider
  local-dir: "${TRAVIS_BUILD_DIR}/gh-pages"
```

**Comment by brianhou** [comment]
Here's a run with both absolute and relative paths: https://travis-ci.org/brianhou/dpl-test/builds/415237528.

**Comment by webknjaz** [comment]
@BanzaiMan @joepvd ^^

**Pull request merged**
