### PR TITLE
Add tests for ruby 2.3

### PR DESCRIPTION
**Pull request by icco**

### CODE REVIEW

**Comment by icco** [comment]
@BanzaiMan PTAL

**Comment by icco** [comment]
P.S. filed https://github.com/rvm/rvm/issues/3697 to try and get things fixed for the 2.3 failure.

**Comment by BanzaiMan** [comment]
The current `rvm` is old and unaware of `2.3`. If you specify `2.3.0` it should work.

**Comment by icco** [comment]
@BanzaiMan from what I can tell it's because binaries for your OS (Precise) and any version of ruby 2.3 don't exist, not because rvm doesn't know about 2.3. If there wasn't the `--binary`, I think it would just work... but maybe I'm misunderstanding.

**Comment by BanzaiMan** [comment]
I'm closing this.

**Pull request closed without merging**
