### PR TITLE
Releases improvements

### LINKED ISSUE #842: [GitHub Releases] Add warning if specified `file` doesn't exist
With the `releases` deployment provider is possible to specify file to be uploaded to the release.

However, if these don't exist, no warnings or errors are printed in the log and the release gets created without these.

It would be convenient to check for the existence of the files and print something in case those don't exist.

### LINKED ISSUE #914: Creating draft GitHub releases breaks tag tying
As soon as I add `deploy.draft: true` to my `.travis.yml`, Travis no longer sets the release's tag to the tag that triggered the Travis build.

This config

```yaml
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  on:
    tags: true
```

results in

bildschirmfoto von 2018-04-07 23-15-05

whereas this config

```yaml
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  draft: true
  on:
    tags: true
```

results in

bildschirmfoto von 2018-04-07 23-29-06

The reason why it says "Existing tag" is not because this tag actually exists (the tag that triggered this Travis build is `v2.0.0-beta.3`), but because GitHub silently and unsolicitedly creates this tag as soon as you hit "Publish"... :unamused: 

It seems like Travis (or GitHub) looses the link between tag and release for some reason when creating a release draft.

This issue can be fixed by explicitly adding the `tag_name` and `target_commitish` variables (see https://github.com/picocms/Pico/commit/6d6a39b74441d68ae33c05dd610ca94d2e4d9b76):

```yaml
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  draft: true
  on:
    tags: true
```

Both variables aren't documented in https://docs.travis-ci.com/user/deployment/releases/

However, I guess it's rather a bug that Travis (or GitHub) doesn't create the release draft using the tag that triggered the Travis build.

Follow-up to #8248

### PR DESCRIPTION
**Pull request by BanzaiMan**
This PR adds to Releases:

1. Message when a file is not uploaded (Resolves #842)
1. Creates a draft release correctly when `draft: true` is passed. (Resolves #914)

### CODE REVIEW

**Comment by BanzaiMan** [comment]
To test:

```yaml
deploy:
  provider: releases
  edge:
    branch: releases-improvements
  ⋮ # rest
```

**Comment by BanzaiMan** [comment]
This might fix #900. (My test shows it, but awaiting confirmation.)

**Comment by xPaw** [comment]
Unsure if this PR is the culprit of the issue I'm seeing, but the timing seems to match.

This PR appears to have broken deploying files to other repositories because target_commitish does not exist in the other repository.

It failed like this:
```Setting target_commitish to e53513b0dcace9014bf54b11508cbbbb9263e085
/home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': PATCH https://api.github.com/repos/thelounge/thelounge/releases/14115585: 422 - Validation Failed (Octokit::UnprocessableEntity)
Error summary:
  resource: Release
  code: invalid
  field: target_commitish // See: https://developer.github.com/v3/repos/releases/#edit-a-release
```
Build: https://travis-ci.com/thelounge/thelounge-deb/builds/92133900
Config: https://github.com/thelounge/thelounge-deb/blob/v3.0.0-rc.5/.travis.yml

It used to work before.

**Comment by BanzaiMan** [comment]
@xPaw Sorry about that. It does indeed seem to be the culprit. Please open a new issue (either here, or on https://travis-ci.community/c/deployment). Thanks.

**Pull request merged**
