### PR TITLE
Avoid setting GIT_HTTP_USER_AGENT in `atlas`, `releases`, and `script`

### PR DESCRIPTION
**Pull request by BanzaiMan**

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Resolves https://github.com/travis-ci/travis-ci/issues/9905.

**Comment by iriberri** [comment]
@BanzaiMan I'm currently debugging this issue happening in the GitHub Releases deployment too. Specifically, when we run `git fetch --tags` to try detect tags on a non-tag build. Do you think we can extend the fix to this provider too? Thank you!

**Comment by iriberri** [comment]
Just updated my comment above with more details :)

**Comment by BanzaiMan** [comment]
The strategy here is to let the `Provider.new` provide the option to remove `GIT_HTTP_USER_AGENT` env var which is already defined when a `DPL::Provider` object is first instantiated.

**Pull request merged**
