### PR TITLE
add --only option to firebase deploy

### PR DESCRIPTION
**Pull request by quibusus**
Firebase allows deploying multiple sites to one firebase project. This option is missing in Travis

https://firebase.google.com/docs/hosting/multisites

`firebase deploy --only hosting:target-name`

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Hello, there.

Is there a test deployment for this PR?

**Comment by quibusus** [comment]
> Hello, there.
> 
> Is there a test deployment for this PR?

Nope, the PR is all there is

**Comment by BanzaiMan** [comment]
Please test it.

**Comment by zpritchett** [comment]
Any progress on this? Definitely would be used in a few projects I'm on.

**Comment by latifs** [comment]
@quibusus, This is a great PR, I really need that, can you update your branch?

**Comment by zpritchett** [comment]
@quibusus @BanzaiMan ... Happy to take this on, what needs to happen to get this moving again?

**Comment by BanzaiMan** [comment]
Please test it. https://github.com/travis-ci/dpl/blob/master/.github/CONTRIBUTING.md#testing-dpl-in-the-context-of-travis-ci-builds

**Comment by quibusus** [comment]
@BanzaiMan thanks for the details 👍 
@zpritchett please, if you have time, please take over 👍

**Comment by svenfuchs** [comment]
@quibusus @zpritchett the option `--only` has been added in master https://github.com/travis-ci/dpl/blob/master/lib/dpl/providers/firebase.rb#L19

The current master has the next major version `v2` which we are about to release. You can opt into using this version by adding:

```
deploy:
  provider: firebase
  edge:
    branch: master
⋮
```

I am going to close this one here. Please feel free to re-open it.

**Pull request closed without merging**
