### PR TITLE
[New Provider] Azure Storage

### PR DESCRIPTION
**Pull request by sato-s**
Recently, MS Azure released [static web hosting](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website) on azure storage.  
This is almost equals to S3 static web hosting.  

I have implemented a new provider that handle azure storage deployment.  
I have tested this with azure free account and this worked successfully.   

If you need additional fix/option/spec etc...  please let me know.

### CODE REVIEW

**Comment by sato-s** [comment]
I did deployment test which I missed.
https://travis-ci.org/sato-s/travis_dpl_test/jobs/510555174

**Comment by svenfuchs** [comment]
Hey @sato-s :wave:

We are working on releasing a new major version dpl v2. The respective branch has been merged to master, and we are planning on releasing a developer preview, as well as a blog post soon, hopefully later this week.

I have ported your work on this branch to a new PR here: https://github.com/travis-ci/dpl/pull/1047. I believe this should be equivalent to your work.

If you would like me to amend the commit in order to add your Git user name and email address please let me know. (My commit was based on your work, so I would happily pass authorship for it, but I also did not want to presume.)

It would be great if you could help us test if the issue that your change was meant to address. You can opt into using dpl v2 by adding this to your `.travis.yml` file:

```yaml
deploy:
  provider: [provider-name]
  edge:
    branch: master
⋮
```

Thank you!

**Comment by sato-s** [comment]
@svenfuchs 

Awesome! I'm happy to hear that!

> If you would like me to amend the commit in order to add your Git user name and email address please let me know.   

Thanks. It' honor to see my name in git log.

I tried deployment with master branch, but it failed with the following error.  

```
Unknown command: azure_storage --access-key=[secure] --account=satodpltesting --dot_match --local-dir=BUILD --fold
```

Can you check this out?

https://travis-ci.org/sato-s/travis_dpl_test/jobs/572566618

**Comment by svenfuchs** [comment]
@sato-s alright, i'll amend the commit!

> I tried deployment with master branch, but it failed with the following error.

OMG i now realize that all the comments i posted on all the ported PRs contain instructions for testing with the master branch, not the PR branch i ported them to. :facepalm:

It should have been:

```
deploy:
  provider: [provider-name]
  edge:
    branch: sf-port-970
```

Could you give it another shot with this branch name?

**Comment by svenfuchs** [comment]
amended the commit: https://github.com/travis-ci/dpl/pull/1047/commits

i'll close this PR here, let's continue the conversation on https://github.com/travis-ci/dpl/pull/1047

**Pull request closed without merging**
