### PR TITLE
Pypi skip removing built packages in dist

### PR DESCRIPTION
**Pull request by madsmtm**
Example job: https://travis-ci.org/madsmtm/fbchat/jobs/394595587

The `pypi` provider automatically removes the genereated packages in the `dist` folder after they've been uploaded, but this can be annoying if you want to reuse those packages later.

I've added the option `skip_remove_build`, default `false`, that prevents this from happening.

The specific use case in mind is when using Github Releases (`releases` provider), and you want to upload the binaries built by `pip`.

I don't know if it's relevant enough to be added, and if it isn't, I'm fine with closing the PR ;)

### CODE REVIEW

**Comment by madsmtm** [comment]
The builds failed, but I can't tell if that's my mistake, or something else :/

**Comment by BanzaiMan** [comment]
@jezdez Is there a good reason that we should run `rm -rf` at all? https://github.com/travis-ci/dpl/commit/8b091fa9ee24bc753cbd5aec24b55e60d0bb33f4 introduced this line a few years ago.

**Comment by jezdez** [comment]
@BanzaiMan Hm, I think I just added this to have some build directory hygiene, since I wasn't sure if there is anything persisted of the build directory when having the cache enabled. 

FWIW the command we use to upload files is `twine upload -r dist/*` meaning that this expects a list of packages to upload, and by default expands to all files found in the `dist/` directory, which is the default target directory of `setup.py`. If there is no persistence between different deploy calls, then we can remove the `rm -rf dist/`.

**Comment by ericziethen** [comment]
Is there any update on the removal of the delete call? I'm hitting the same issue as the original poster.

**Comment by svenfuchs** [comment]
Hey @madsmtm :wave:

We are working on releasing a new major version dpl v2. The respective branch has been merged to master, and we are planning on releasing a developer preview, as well as a blog post soon, hopefully later this week.

I have ported your work on this branch to a new PR here: https://github.com/travis-ci/dpl/pull/1036. I believe this should be equivalent to your work.

If you would like me to amend the commit in order to add your Git user name and email address please let me know. (My commit was based on your work, so I would happily pass authorship for it, but I also did not want to presume.)

It would be great if you could help us test if the issue that your change was meant to address. You can opt into using dpl v2 by adding this to your `.travis.yml` file:

```yaml
deploy:
  provider: [provider-name]
  edge:
    branch: master
⋮
```

Thank you!

**Comment by svenfuchs** [comment]
i have merged https://github.com/travis-ci/dpl/pull/1036. i am going to close this one here. please feel free to reopen if needed.

**Pull request closed without merging**
