### PR TITLE
Install mime-types

### PR DESCRIPTION
**Pull request by rgbkrk**
Fix for #369 (or so I hope)

### CODE REVIEW

**Comment by BanzaiMan** [comment]
I don't think this will work, if the issue is similar to #366 or #368.

**Comment by rgbkrk** [comment]
I'm tempted to just replace the cloudfiles provider with a go binary, that of [`rack`](https://github.com/rackspace/rack). Fog can be... tumultuous.

**Comment by BanzaiMan** [comment]
@rgbkrk It is worth a try. In the meantime, I'm closing this PR.

**Comment by rgbkrk** [comment]
All good, thanks.

**Pull request closed without merging**
