### PR TITLE
Allow users to specify default text charset

### PR DESCRIPTION
**Pull request by icco**
We're running into issues where AWS isn't getting our charset right. This allows us to specify it for text files.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Please update the PR with the master branch and try again. Thanks.

**Comment by icco** [comment]
@BanzaiMan Done! Thanks.

**Comment by BanzaiMan** [comment]
Looks ready. Could you update README, and open a PR for [docs](https://github.com/travis-ci/docs-travis-ci-com) as well?

**Comment by icco** [comment]
I have updated the Readme. Will open a PR for docs.

**Comment by BanzaiMan** [comment]
@icco https://github.com/travis-ci/docs-travis-ci-com/blob/gh-pages/user/deployment/s3.md is the S3 document.

**Comment by icco** [comment]
I've sent in a docs PR.

**Pull request merged**
