### PR TITLE
Improved and updated the Deis provider

### PR DESCRIPTION
**Pull request by aj-may**

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
:+1: (Deis intern working on deis cli) This is a nice move, since the deis client is going to be changing from python to go in the next few releases, and using a URL to download allows transparent selection between the two.

However, you also need to update the deis provider tests :smiley:

**Comment by aj-may** [comment]
@Joshua-Anderson Updated the tests.  Still getting a failure on 2.1.0, but I think its a dependency issue.

**Comment by aj-may** [comment]
@BanzaiMan Would you mind taking a look over this PR?

**Comment by aj-may** [comment]
@Joshua-Anderson @BanzaiMan Tests passing, and I tested it in the travis containerized env.  Everything seems to be working great.

**Comment by jorihardman** [comment]
:+1: Thanks for working on this @aj-may - you beat me to the punch. @BanzaiMan Can we get this merged in ASAP please? It would be great to have travis deploys back.

**Comment by BanzaiMan** [comment]
OK. This inexplicably breaks a PyPI spec, so I've reverted it.

**Comment by BanzaiMan** [comment]
All right. I've fixed the problem by tweaking the seemingly unrelated spec. You can test this with a following:

```yaml
deploy:
  provider: deis
  edge: true # <= new!
  ⋮ # rest
```

However, this PR changes the way git ssh is set up, and I'm afraid the effects might be far reaching. In particular, Heroku's git strategy will be affected. Perhaps it is better to completely override `#setup_git_ssh` and not call `super`.

**Comment by BanzaiMan** [comment]
OK. I've tweaked the Deis provider, so that it does not affect others. Please test it with `edge: true`. Thanks.

**Comment by BanzaiMan** [comment]
This has been released to 1.7.20.

**Comment by aj-may** [comment]
@BanzaiMan Thank you!

**Pull request merged**
