### PR TITLE
Fixed provider anynines to work in TravisCI

### PR DESCRIPTION
**Pull request by benjaminguttmann-avtq**
Now cf api endpoint is set correctly, furthermore user can login and set organization and spaces.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Sorry for the delay. What is the problem this PR aims to solve? Do you have a build log URL that shows this problem? Has this PR been tested?

**Comment by benjaminguttmann-avtq** [comment]
If you want to deploy something to the provider anynines you get the following log:

cf
dpl.3
Deploying application
No API endpoint set. Use 'cf login' or 'cf api' to target an endpoint.
FAILED
No org and space targeted, use 'cf target -o ORG -s SPACE' to target an org and space
Logging out...
OK

With the changes the provider should work correctly.

**Comment by BanzaiMan** [comment]
@benjaminguttmann-avtq Where would I see this error message?

Perhaps I am missing something, but I fail to see how this PR would resolve any error that results in a message like that. This PR changes the location of the `cf` executable to the current directory, and current directory only.

A likely cause of your error is missing arguments, perhaps because you tried encrypting values but that failed for one reason or another.

Please follow instructions in https://github.com/travis-ci/dpl/blob/master/TESTING.md to test this PR, and please link to the build that resolves deployment issue.

**Comment by benjaminguttmann-avtq** [comment]
So, here is the link to the build with my changes: https://travis-ci.org/benjaminguttmann-avtq/ruby-sinatra-example-app/builds/101559287

**Pull request merged**
