### PR TITLE
Deis provider needs to execute push in bash

### PR DESCRIPTION
**Pull request by mattk42**
#479 wasn't working as expected. PIPESTATUS is a bash feature and the context.shell is a simple sh session. The result of this would be that all deploys would get marked as failed. 

To fix this I am executing the deployment in a bash session.

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
@BanzaiMan is there anything that needs to happen for this to be merged?

**Comment by BanzaiMan** [comment]
Sorry about the delay. I was traveling a bit.

**Comment by BanzaiMan** [comment]
Has this been tested anywhere? If not, please rebase this beforehand. (I don't think it is a big deal, but the red text still scares me.)

**Comment by mattk42** [comment]
I have been running from my own branch that has this and #440 merged together with no issues. I will go ahead and rebase.

**Pull request merged**
