### PR TITLE
Add app_name option to Cloud Foundry provider

### LINKED ISSUE #699: Allow APP_NAME in cloudfoundry
It would be great can set `APP_NAME` in the cloudfoundry provider.

Something like:

```yaml
deploy:
  - provider: cloudfoundry
    username: apikey
    password: $BLUEMIX_API_KEY
    api: https://api.ng.bluemix.net
    organization: $BLUEMIX_ORGANIZATION
    space: $BLUEMIX_SPACE
    manifest: manifest.yml
    app_name: $APP_NAME  # <= Set the app name
    skip_cleanup: true
    on:
      branch: master
```

### PR DESCRIPTION
**Pull request by abdonrd**
Fixes #699.

### CODE REVIEW

**Comment by abdonrd** [comment]
Friendly ping to @BanzaiMan.

**Comment by BanzaiMan** [comment]
Thanks for the PR and sorry for the long delay. As I am not entirely familiar with Cloud Foundry, could you educate me on how the app name (which appears to be a required argument to `cf push`) is computed when it is not explicitly given?

Also, could you point to a test deployment using this PR?

Thanks again!

**Comment by abdonrd** [comment]
@BanzaiMan I share you the official documentation:

> Run the following command to deploy an app without a manifest:
> 
> `cf push APP-NAME`
> 
> If you provide the app name in a manifest, you can reduce the command to cf push. See Deploying with Application Manifests.

From: [Cloud Foundry docs => Deploy an Application => Step 5: Push the App](https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html#push)

About the test deployment using this PR, how should I do it?

**Comment by abdonrd** [comment]
Example with [Qiskit/qiskit.org](https://github.com/Qiskit/qiskit.org):

* [.travis.yml](https://github.com/Qiskit/qiskit.org/blob/master/.travis.yml)

https://github.com/Qiskit/qiskit.org/blob/a6dd5b9ffc92559f8e08ea6a25da51a6f2e1bfde/.travis.yml#L13-L22

* [server / prpl / manifest.yml](https://github.com/Qiskit/qiskit.org/blob/master/server/prpl/manifest.yml)

https://github.com/Qiskit/qiskit.org/blob/a6dd5b9ffc92559f8e08ea6a25da51a6f2e1bfde/server/prpl/manifest.yml#L1-L9

**Comment by BanzaiMan** [comment]
Could you point to a test deployment using this PR? Thanks.

**Comment by abdonrd** [comment]
@BanzaiMan I already asked before: About the test deployment using this PR, how should I do it! Thanks in advance!

**Comment by BanzaiMan** [comment]
Ah, sorry. I skipped your question earlier. This process is explained in https://github.com/travis-ci/dpl/blob/master/.github/CONTRIBUTING.md#testing-dpl-in-the-context-of-travis-ci-builds. Thanks a bunch!

**Comment by abdonrd** [comment]
@BanzaiMan thanks for the link, tomorrow I will do the test!

**Comment by abdonrd** [comment]
@BanzaiMan it works! 🎉 

- https://github.com/Qiskit/qiskit.org/commit/74fc783ef7c82cd4dc52a21220b9f18db8e56e59
- https://travis-ci.org/Qiskit/qiskit.org/builds/449110112

**Comment by BanzaiMan** [comment]
Super! Please update README in this repo, and open a docs PR at https://github.com/travis-ci/docs-travis-ci-com/, please. Do note that cloudfoundry has a few child providers which will be affected by this change.

Thanks.

**Comment by abdonrd** [comment]
@BanzaiMan both done!

https://github.com/travis-ci/docs-travis-ci-com/pull/2101

**Comment by BanzaiMan** [comment]
Hi, @abdonrd! Thank you for that. I am sorry, but I think I misinformed you about the code layout. Earlier this year, I changed the class hierarchy, so that the CloudFoundry "children" are no longer descendants of it. A series of commits will explain this; e.g., https://github.com/travis-ci/dpl/commit/d15c0f838291961459d5b5b05d1b88db49df06af.

So, this PR would benefit from duplicating it in other CloudFoundry-like providers (anynines, bluemix):

```sh-session
$ ack -w cf --ruby -l lib
lib/dpl/provider/cloud_foundry.rb
lib/dpl/provider/bluemix_cloud_foundry.rb
lib/dpl/provider/anynines.rb
```

**Comment by abdonrd** [comment]
@BanzaiMan hopefully done! haha

**Pull request merged**
