### PR TITLE
npm: port alias from travis-yml and dpl v2

### PR DESCRIPTION
**Pull request by native-api**
https://travis-ci.community/t/npm-deploy-failed-missing-api-key-but-i-have-set-it/6624

### CODE REVIEW

**Comment by Ionaru** [comment]
Any ETA on merging this PR?

**Comment by BanzaiMan** [comment]
Test, please.

**Comment by BanzaiMan** [comment]
Sorry, I wasn't clear. Please point to a test deployment. Thanks.

**Comment by native-api** [comment]
https://travis-ci.org/native-api/micro-web-service/jobs/637790937
I don't own any NPM packages so deployment failed but you can see in the log that the API key is being recognized.

**Pull request merged**
