### PR TITLE
Fix Scalingo login, use their cli new flag

### PR DESCRIPTION
**Pull request by Soulou**

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Hello, there! Thanks for the PR. Could you add a build log URL that shows the deployment using this code?

**Comment by Soulou** [comment]
@BanzaiMan Yep it's coming

**Comment by Soulou** [comment]
Here it is

```
└> ~/Sources/dpl/bin/dpl --provider=scalingo --api-key=xxxxxxxxxxxxxxxx --app=sample-go-martini --remote=test-dpl
Installing deploy dependencies
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3991k  100 3991k    0     0  1027k      0  0:00:03  0:00:03 --:--:-- 1027k
scalingo_1.8.0_linux_amd64/
scalingo_1.8.0_linux_amd64/scalingo
scalingo_1.8.0_linux_amd64/LICENSE
scalingo_1.8.0_linux_amd64/README.md
Preparing deploy
Generating public/private rsa key pair.
Your identification has been saved in .dpl/id_rsa.
Your public key has been saved in .dpl/id_rsa.pub.
The key fingerprint is:
SHA256:GMcJLvIVSMjyJ8wsyL2+Fq48+OuFbpZqzPv5l75uWeM soulou7
The key's randomart image is:
+---[RSA 2048]----+
| . o..o          |
|. o .. + .       |
|o*o . + +        |
|o.*+.o +         |
| . oo . S        |
|   +     o       |
|+ +.o   = .      |
|o*+=.  = E       |
|oX@=o.=+.        |
+----[SHA256]-----+
Key 'dpl_tmp_key' has been added.
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.
Saved working directory and index state WIP on master: f4cbb4b test
Deploying application
Warning: Permanently added 'scalingo.com' (RSA) to the list of known hosts.
Counting objects: 33, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (31/31), done.
Writing objects: 100% (33/33), 9.90 KiB | 675.00 KiB/s, done.
Total 33 (delta 17), reused 0 (delta 0)
 <-- Start deployment of sample-go-martini -->
       Fetching source code
       Fetching deployment cache
-----> Using buildpack 'go'
-----> Checking Godeps/Godeps.json file.
-----> Using go1.9.4
 !!    Installing package '.' (default)
 !!    
-----> Running: go install -v -tags paas . 
github.com/Scalingo/sample-go-martini/vendor/github.com/codegangsta/inject
github.com/Scalingo/sample-go-martini/vendor/github.com/oxtoacart/bpool
github.com/Scalingo/sample-go-martini/vendor/github.com/go-martini/martini
github.com/Scalingo/sample-go-martini/vendor/github.com/martini-contrib/render
github.com/Scalingo/sample-go-martini
-----> Procfile declares types -> web
       
-----> Build complete, uploading deployment cache.
-----> .slugignore detected, cleaning project before packaging
       '/Godeps' has been removed from the image
 Build complete, shipping your container...
 Waiting for your application to boot... 
 <-- https://sample-go-martini.scalingo.io -->
```

**Comment by BanzaiMan** [comment]
@Soulou Please test it using the steps described in https://github.com/travis-ci/dpl/blob/master/.github/CONTRIBUTING.md#testing-dpl-in-the-context-of-travis-ci-builds. Thanks.

**Comment by Soulou** [comment]
@BanzaiMan here it is: https://travis-ci.org/Scalingo/sample-go-martini/builds/360560334

**Comment by BanzaiMan** [comment]
Thanks!

**Comment by Soulou** [comment]
Is it possible to schedule a release of `dpl` as currently event by fetching the `dpl` gem from master, as it installs the last stable provider gem `dpl-scalingo`, this patch is not usable.

Thanks a log.

**Pull request merged**
