### PR TITLE
Add Cloudformation provider

### PR DESCRIPTION
**Pull request by radekl**
Hello!

This cloudformation provider enables 5 cloudformation actions:
- Create a create change set (https://travis-ci.org/radekl/travis-dpl-test/builds/484027713)
- Create an update change set (https://travis-ci.org/radekl/travis-dpl-test/builds/484254601)
- Create stack (https://travis-ci.org/radekl/travis-dpl-test/builds/484255422)
- Update stack (https://travis-ci.org/radekl/travis-dpl-test/builds/484255971)
- No changes/skip deployment (https://travis-ci.org/radekl/travis-dpl-test/builds/484257093)

Those five actions are sufficient to deploy most of the stacks. 
Included all builds for all types of actions.

Please be aware that those build may currently fail because of disabled AWS secrets. Those builds were just a demo showing that this provider works properly.

Also using multiple account through `sts_assume_role` works really nice (aws ruby sdk for cloudformation doesn't allow to make cross-account operations - this is bypassed by using STS client and receiving new temporary credentials for different account. Commits: c6da9dd and 16649ee).

### CODE REVIEW

**Comment by radekl** [comment]
Missing README.md entry. Will add it at Monday.

**Comment by svenfuchs** [comment]
Hey @radekl :wave:

We are working on releasing a new major version dpl v2. The respective branch has been merged to master, and we are planning on releasing a developer preview, as well as a blog post soon, hopefully later this week.

I have ported your work on this branch to a new PR here: https://github.com/travis-ci/dpl/pull/1050. I believe this should be equivalent to your work.

If you would like me to amend the commit in order to add your Git user name and email address please let me know. (My commit was based on your work, so I would happily pass authorship for it, but I also did not want to presume.)

It would be great if you could help us test if the issue that your change was meant to address. You can opt into using dpl v2 by adding this to your `.travis.yml` file:

```yaml
deploy:
  provider: [provider-name]
  edge:
    branch: master
⋮
```

Thank you!

**Comment by radekl** [comment]
That's great that you've had time to do such amazing job! Getting straight to testing. I don't mind being mentioned, but at the same time it's totally not important for me. The provider itself is what matters :)

**Comment by svenfuchs** [comment]
@radekl that's awesome, thank you!

i should have mentioned that this is the one PR i've ported where i have a local note "needs more tests" :) i'll see about adding those asap.

going to close this PR here, let's continue the conversation on https://github.com/travis-ci/dpl/pull/1050

**Pull request closed without merging**
