### PR TITLE
Bintray: Automatically add artifacts to downloads list 

### LINKED ISSUE #944: Bintray: Automatically add artifacts to downloads list
Hi there!

It would be great if we could specify artifacts to appear in the featured download list for Bintray.

It could be done using a specific API call on uploaded content: https://www.jfrog.com/confluence/display/BT/Bintray+REST+API#BintrayRESTAPI-FileinDownloadList 

Looks like this issue was already reported (#565) but never implemented and automatically closed by  a bot.

### PR DESCRIPTION
**Pull request by loicalbertin**
This PR fixes #944 
The idea is to allow files in the Bintray file descriptor to be tagged as they should appear in the download list. This way we can select some files to appear in this list and some not (disabled by default).

The tricky part here is that a version should be published before selecting artifacts to appear in the download list. So this feature is disabled if the `publish` is not set to `true` in the file descriptor.
Linked to the publication another trick is while the API responds instantaneously OK to a version publication it takes actually some time (up to 15s in my tests) to be effective. So I had to implement a retry mechanism.

Tested in real conditions using this bintray account: https://bintray.com/beta/#/loicalbertin/dpl-test/auto-upload/
And this Github project https://github.com/loicalbertin/travis-dpl-bintray-test
travis: https://travis-ci.org/loicalbertin/travis-dpl-bintray-test

I updated the bintray file descriptor in README to document this feature.

Please feel free to adapt/tweak retry parameters.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
What do these error responses from Bintray mean?

https://travis-ci.org/loicalbertin/travis-dpl-bintray-test/jobs/483352794#L571-L577

**Comment by BanzaiMan** [comment]
> An error 400 is returned when trying to put in download list an unpublished file.

Is this generally known? I don't want users to see the 4xx response and be alerted.

Is it possible to wrap this in a nice message, perhaps, to make it clear that there is nothing to worry about?

**Comment by loicalbertin** [comment]
> Is this generally known? 

This what I experienced but afaik it is not documented in the bintray API.

> Is it possible to wrap this in a nice message, perhaps, to make it clear that there is nothing to worry about?

Or we can make a preventive sleep of 15s or 20s. What do you prefer?

**Comment by loicalbertin** [comment]
Hi @BanzaiMan 

I took your remarks into account:

* I tried to make the message less scary but still printing something to give feedback to the user.
* I tweaked the retries values we will now wait for 10s before retrying and give up after 5 tries
* The original Bintray message will be printed only when we definitely give up

You can see the result here: <https://travis-ci.org/loicalbertin/travis-dpl-bintray-test/builds/490566618#L566-L569>

WDYT?

**Comment by loicalbertin** [comment]
@BanzaiMan any news regarding this?

**Comment by devnoname120** [comment]
@BanzaiMan This is also a major pain point for me as users have trouble finding downloads. Any updates?

**Comment by laurentganne** [comment]
+1 !

**Comment by loicalbertin** [comment]
Hi @BanzaiMan,

Any chance to see this merged ?
I have another contribution in mind, but I'm a bit desperate to see this on integrated and  I'm not sure to do it finally....

**Comment by svenfuchs** [comment]
Hey @loicalbertin :wave:

We are working on releasing a new major version dpl v2. The respective branch has been merged to master, and we are planning on releasing a developer preview, as well as a blog post soon, hopefully later this week.

I have ported your work on this branch to a new PR here: https://github.com/travis-ci/dpl/pull/1045. I believe this should be equivalent to your work.

If you would like me to amend the commit in order to add your Git user name and email address please let me know. (My commit was based on your work, so I would happily pass authorship for it, but I also did not want to presume.)

It would be great if you could help us test if the issue that your change was meant to address. You can opt into using dpl v2 by adding this to your `.travis.yml` file:

```yaml
deploy:
  provider: [provider-name]
  edge:
    branch: master
⋮
```

Thank you!

**Comment by loicalbertin** [comment]
Hi @svenfuchs 

Sorry for the delay I was off last week.
That's great to see this ported on a new dpl version!
Unfortunately it fails when I try to test your branch https://travis-ci.org/loicalbertin/travis-dpl-bintray-test/jobs/573852224#L286

Regarding commit authorship do it as you usually do, no problem from my side.

**Comment by loicalbertin** [comment]
Hi @svenfuchs, 

By creating #1074 I had a better look at #1045 and for me it's a total rewrite, authorship is yours :smile:

**Comment by svenfuchs** [comment]
With https://github.com/travis-ci/dpl/pull/1045 merged I guess we can close this one here? Feel free to reopen if needed.

**Pull request closed without merging**
