### PR TITLE
Relax chef gem constraint for chef-supermarket provider

### PR DESCRIPTION
**Pull request by kamaradclimber**
dpl is now running with ruby 2.2.7 so we don't have to restrain
chef version too much

Also fix compatibility with recent chef version.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
This is not strictly true. While much smaller in number, there are Precise images that still require 1.9 support.

**Comment by kamaradclimber** [comment]
Thanks for the feedback.
Can those images be used for builds targetting `language: ruby` ? (which is used by builds using chef_supermarket provider)

**Comment by kamaradclimber** [comment]
@BanzaiMan would you have any feedback/advice to get this PR merged?

**Comment by kamaradclimber** [comment]
@BanzaiMan what can we do with this PR?

**Comment by BanzaiMan** [comment]
Please test this PR, on both Trusty and Precise.

We are also looking at dropping Ruby 1.9 support from `dpl`, but that may take a little while longer.

**Comment by kamaradclimber** [comment]
I've made a patch which is backward compatible with old ruby versions.

**Comment by BanzaiMan** [comment]
Thanks. Has it been tested?

**Comment by Annih** [comment]
@BanzaiMan I personally tested it on some chef cookbooks. It works fine for me.

**Comment by BanzaiMan** [comment]
With #757, chef_supermarket now resolves to 13.8.0 (as of this writing).

**Pull request closed without merging**
