### PR TITLE
Update hackage.rb

### PR DESCRIPTION
**Pull request by sol**
As of `cabal-2.0.*` it's required to pass `--publish` to `cabal upload`.

### CODE REVIEW

**Comment by sol** [comment]
Upfront, sorry if this requires spec changes, too.  I created this PR through GitHub and did not run the specs.

**Comment by BanzaiMan** [comment]
Hello, there. Sorry for the delay. I'm reorganizing code for the 1.9.0 release, so PRs are on hold until I can get that out of the way. Deployment provide code should not be affected, but I do not plan to have another release before 1.9.0.

Thank you for your understanding.

**Comment by sol** [comment]
@BanzaiMan well, currently the "feature" is broken.

**Comment by BanzaiMan** [comment]
@sol For the time being, you can deploy with your fork by following the instructions in https://github.com/travis-ci/dpl/blob/master/.github/CONTRIBUTING.md

**Comment by BanzaiMan** [comment]
Sorry for the long delay. Could you test again? We are well past 1.9.0 now.

**Comment by svenfuchs** [comment]
Hey @sol :wave:

We are working on releasing a new major version dpl v2. The respective branch has been merged to master, and we are planning on releasing a developer preview, as well as a blog post soon, hopefully later this week.

I have ported your work on this branch to a new PR here: https://github.com/travis-ci/dpl/pull/1033. I believe this should be equivalent to your work.

If you would like me to amend the commit in order to add your Git user name and email address please let me know. (My commit was based on your work, so I would happily pass authorship for it, but I also did not want to presume.)

It would be great if you could help us test if the issue that your change was meant to address. You can opt into using dpl v2 by adding this to your `.travis.yml` file:

```yaml
deploy:
  provider: [provider-name]
  edge:
    branch: master
⋮
```

Thank you!

**Comment by svenfuchs** [comment]
https://github.com/travis-ci/dpl/pull/1033 has been merged. i'm going to close this PR here. please feel free to reopen if needed.

**Pull request closed without merging**
