### PR TITLE
Fixed file-specific Cache-Control and Expires headers in S3 provider

### PR DESCRIPTION
**Pull request by chriselsen**
Fixed setting of file-specific Cache-Control and Expires headers using value: file[, file] format in S3 provider. 
Now supports: 
--cache_control="no-cache: index.html"
--expires="\"2012-12-21 00:00:00 -0000\": *.css, *.js"

This should address issue #486

### CODE REVIEW

**Comment by chriselsen** [comment]
Nested file support for 
--cache_control="max-age=99999999, no-cache: foo.html, bar.txt, max-age=9999: *.txt"

uploading "foo.html" with {:content_type=>"text/html", :cache_control=>"no-cache", :acl=>"public-read", :expires=>nil}
uploading "baz.js" with {:content_type=>"application/javascript", :cache_control=>"max-age=99999999", :acl=>"public-read", :expires=>nil}
uploading "bar.txt" with {:content_type=>"text/plain", :cache_control=>"max-age=9999", :acl=>"public-read", :expires=>nil}

**Comment by chriselsen** [comment]
The test at https://github.com/travis-ci/dpl/blob/master/spec/provider/s3_spec.rb for "Sets different Cache and Expiration" seems to be having some issues:

Running manually: 
--cache_control="max-age=99999999, no-cache: foo.html, bar.txt, max-age=9999: *.txt" --expires="\"2012-12-21 00:00:00 -0000\", \"1970-01-01 00:00:00 -0000\": *.html"

comes back with:
Deploying application
Beginning upload of 3 files with 1 threads.
uploading "foo.html" with {:content_type=>"text/html", :cache_control=>"no-cache", :acl=>"public-read", :expires=>"1970-01-01 00:00:00 -0000"}
uploading "baz.js" with {:content_type=>"application/javascript", :cache_control=>"max-age=99999999", :acl=>"public-read", :expires=>"2012-12-21 00:00:00 -0000"}
uploading "bar.txt" with {:content_type=>"text/plain", :cache_control=>"max-age=9999", :acl=>"public-read", :expires=>"2012-12-21 00:00:00 -0000"}

From what I can tell that's what the spec requires.

**Comment by chriselsen** [comment]
Need to investigate further. While dpl is working standalone, the config is not correctly passed from travis.yml

**Comment by chriselsen** [comment]
The issue is that Travis-YML only passes a string for cache-control and expires. Therefore it seems that no work was ever implemented here to pass a YAML array. 

With the above fixes and the following .travis.yml config snippet it does work:
cache_control: "max-age=31536000: *.jpg, *.gif, *.png, *.webp, *.css, *.js, *.ico"
expires: "\"2030-12-31 00:00:00 -0000\": *.jpg, *.gif, *.png, *.webp, *.css, *.js, *.ico"


See https://travis-ci.com/edge-cloud/www.edge-cloud.net/builds/101230805 for a successful build.

**Comment by chriselsen** [comment]
See https://github.com/edge-cloud/www.edge-cloud.net/blob/master/.travis.yml for working config
and https://travis-ci.com/edge-cloud/www.edge-cloud.net/builds/101237497 for successful build.

**Comment by chriselsen** [comment]
Please clarify how file-specific cache-controls are working today. #486 is about how this isn't working. Also please read my comment there, which outlines in detail why the current approach cannot be made to work.

**Comment by BanzaiMan** [comment]
The comment tells you that only the last one is effective.

**Comment by chriselsen** [comment]
In the example of 
```
 - provider: s3
    ...
    cache_control:
      - "max-age=300": "*.js"
      - "max-age=3000":
        - "*.css"
        - "*.png"
      - "no-cache"
```
the YAML is not passed on to dpl, as travis-yml is not setup to do this. All that is passed from travis-yml to dpl is: `cache_control=>"no-cache"`. I explained that in #486 in great detail and also why there is no way to make the YAML style configuration work without major changes to travis-yml. 
Such a change would then also be inconsistent to the [dpl documentation](https://github.com/travis-ci/dpl#s3). 

Go ahead and change in `dpl/lib/dpl/provider/s3.rb` line 113 from `log "uploading #{filename.inspect} with #{opts.inspect}"` to `log "uploading #{filename.inspect} with #{opts.inspect} --> #{options} <--"`. Then run a deployment and look at what is actually passed from travis-yml to dpl.

**Comment by viniciuskneves** [comment]
Any updates here? Or is this issue being addressed somewhere else?

**Comment by chriselsen** [comment]
@BanzaiMan Where are we with this?

**Comment by matthewfaircliff** [comment]
Hello. Is there any activity progress likely here? [#486 ](https://github.com/travis-ci/dpl/issues/486) was opened 3 years and references this problem. We are keen TravisCI users but this is a deal breaker as now we need to write post deployment logic to handle this.

**Comment by svenfuchs** [comment]
I have ported this PR to the new `master` (dpl v2) here with some minor adjustments, mostly making the format more tight: https://github.com/travis-ci/dpl/pull/1062

@chriselsen since i have ported your work i would happily pass over authorship to you, and amend the commit with your git author name and email, but i also did not want to assume. Please let me know, and i'll amend the commit.

@chriselsen @viniciuskneves @matthewfaircliff it would be amazing if you could try this out.

I am going to close this issue here. Let's continue the conversation on https://github.com/travis-ci/dpl/pull/1062

**Comment by chriselsen** [comment]
> @chriselsen since i have ported your work i would happily pass over authorship to you, and amend the commit with your git author name and email, but i also did not want to assume. Please let me know, and i'll amend the commit.

Thanks for the consideration and glad to see that this is finally coming to fruition. Please go ahead and amend the commit. Thank you!

**Comment by svenfuchs** [comment]
@chriselsen sure thing, done: https://github.com/travis-ci/dpl/pull/1062/commits/332e6d6a5ff78379d6a0a8819008f800e1e60734

**Pull request closed without merging**
