### PR TITLE
Fix xenial pages error test

### PR DESCRIPTION
**Pull request by biodranik**
This PR is created to test https://github.com/travis-ci/dpl/pull/966#issuecomment-474579575

### CODE REVIEW

**Comment by BanzaiMan** [comment]
PR builds don't trigger deployments. Please use your own repository to test it. Thanks.

**Comment by biodranik** [comment]
@BanzaiMan I'm not sure how to do it. Can you please provide a more detailed step-by-step instruction?
What should I do with a test .travis.yml ? Should I refer there some other repo with a real pages deploy content? Should I do a PR to my own clone of DPL? Any other configuration steps?

**Comment by BanzaiMan** [comment]
@biodranik There is a link to it from our README. https://github.com/travis-ci/dpl#writing-and-testing-a-new-deployment-provider-and-new-functionality

**Comment by BanzaiMan** [comment]
Enable Travis CI on your own repository, and trigger a deployment using the configuration described in the documentation.

**Comment by biodranik** [comment]
@BanzaiMan I've tried that, but build fails due to some bug in heroku: https://travis-ci.org/biodranik/dpl/jobs/510652848

**Comment by BanzaiMan** [comment]
The testing is not about specs we run automatically, but the deployment your fork would run, using the deployment provider you want to modify. Unless you've set up your `dpl` fork to deploy to RubyGems.org, the error in https://travis-ci.org/biodranik/dpl/jobs/510652848 has little bearing on your test (although it is a curious failure).

What I am asking of you is a repository set up to deploy to GitHub Pages, and a successful deployment using your PR.

**Comment by biodranik** [comment]
@BanzaiMan Thanks for your time, I've updated my PR #966 with a link to a successful test in my own repo. I'm closing this PR as a not relevant one.

**Pull request closed without merging**
