### PR TITLE
Fix #291, add support for S3 storage class

### LINKED ISSUE #291: Allow to select reduced redundancy storage option when deploying to S3
Amazon allows to select reduced redundancy storage when uploading object. It would be great if the S3 deployer would allow that. Especially for build-artifacts which can easily regenerated this would be a nice-to-have option.

### PR DESCRIPTION
**Pull request by englercj**
Add support for S3 Storage Classes.

AWS Docs here: https://aws.amazon.com/s3/storage-classes/

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Thanks for the PR. Has this been tested?

**Comment by englercj** [comment]
Yes, I used [this commit](https://github.com/Fae/fae/commit/87802b305f595ebd16c3aa03c436e83bc8331570) to use my fork of this gem, and specify a storage class. It ran in [this build](https://travis-ci.org/Fae/fae/builds/152680756), which deployed the files correctly to my S3 instance:

image

I will also rebase this branch onto the latest master.

**Comment by englercj** [comment]
Now that this has been merged, when will it be available on Travis? Just so I know when to remove my edge config

**Comment by BanzaiMan** [comment]
You'd need:

```yaml
deploy:
  provider: s3
  edge: true
```

until there is a release.

**Pull request merged**
