### PR TITLE
Add TestFairy provider

### PR DESCRIPTION
**Pull request by BanzaiMan**
This PR supersedes #223.

Fixes indentations, and makes the code a bit more Ruby-esque.

### CODE REVIEW

**Comment by testfairy** [comment]
Hi @BanzaiMan PR #223 was updated (spec file added), can you please pull the code.

**Comment by BanzaiMan** [comment]
@testfairy Could you review?

**Comment by testfairy** [comment]
@BanzaiMan Looks great! Thanks for the code review and fixes. Can't wait to see it online! :)
:smile_cat: 

Anything else I can help with?

**Comment by BanzaiMan** [comment]
@testfairy The spec fails now, due to an empty .apk file (https://travis-ci.org/travis-ci/dpl/jobs/57500939#L396) Not sure how it [worked before](https://travis-ci.org/travis-ci/dpl/builds/56673951).

**Comment by testfairy** [comment]
@BanzaiMan Oops, it was a temporary bug we had on the download server. It has been fixed and shouldn't happen again. Can you please re-run travis job?

**Comment by BanzaiMan** [comment]
Cool. It succeeded. https://travis-ci.org/travis-ci/dpl/builds/57667464

You can test the deployment provider with

```yaml
deploy:
  provider: testfairy
  edge: true
  ⋮
```

**Comment by BanzaiMan** [comment]
@testfairy Could you test it, please? Thank you!

**Pull request merged**
