### PR TITLE
Added additional logging to s3 provider

### PR DESCRIPTION
**Pull request by thetron**
This is a reasonably trivial commit, but I thought it might help to have a bit of logging output for S3 deploys. We've also had some issues on our (really) long S3 deploys hitting the 10 minute timeout, and though the extra logs might help here?

### CODE REVIEW

**Comment by BanzaiMan** [comment]
So sorry for dropping the ball. Could you rebase this and we will take a look soon! Thank you! <3

**Comment by BanzaiMan** [comment]
We've updated S3 provider, so we'll really need a rebase. :-D

**Comment by thetron** [comment]
Sorry @BanzaiMan I totally missed your last comment (in July!). I think - in its current state - the output is verbose enough for me. As much as I'd love to get a contrib in there - I don't really know if there is a real need for this anymore?

**Comment by BanzaiMan** [comment]
@thetron Thanks for the input, and the effort you've put in. I am going to close this for now, then. Thanks again!

**Pull request closed without merging**
