### PR TITLE
Provide `quiet` option to S3 provider

### PR DESCRIPTION
**Pull request by BanzaiMan**
Users may end up uploading thousands of files, which will eat up log 
capacity.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
This could be a useful option for other potentially noisy providers, but we'll start from here.

**Comment by soulim** [comment]
@BanzaiMan thanks a lot for adding this option. Have you considered a common option for all providers and not just S3? Then it would allow consistent behaviour for all providers.

If I'm not mistaken it should be enough to add conditional logging in this line: https://github.com/travis-ci/dpl/blob/2f13fcaff5293d7463660321c0a197fa1e62ef58/lib/dpl/provider.rb#L294

Something like this:

```ruby
def log(message)
  $stderr.puts(message) unless options[:quiet]
end
```

**Comment by BanzaiMan** [comment]
@soulim I have not considered it. It could work, but I am afraid that doing so without examining each deployment provider's behavior could make diagnosis hard in the case of problems.

**Comment by BanzaiMan** [comment]
I didn't mean to do that.

**Comment by BanzaiMan** [comment]
See #882 for further discussion.

**Pull request merged**
