### PR TITLE
Remove python requirement for dpl-v2 google cloud storage

### PR DESCRIPTION
**Pull request by wojm**
I don't know if this is right, but it helped with my project

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Curious. Could you point to the test deployment, please? (And if it was failing without, please point to a failing one, too.)

**Comment by wojm** [comment]
config:
```
---
os: linux
language: node_js
node_js: 10

dist: trusty

cache: npm # cache build based on npm

jobs:
  include:
    - stage: test # define stage called test, it propogates until it is overwritten
      script: npm run lint:hbs
      name: lint hbs
    - script: npm run lint:js
      name: lint javascript
    - script: npm run test:ember
      name: test ember app
      addons:
        chrome: stable # chrome browser for tests

    - stage: deploy
      if: branch = master AND type = push AND fork = false
      branch: master
      script: echo 'Deploying'
      name: deploy application
      install: true # don't need to install
      deploy:
        provider: heroku:git
        api_key: $HEROKU_API_KEY
        edge: true # use v2
        cleanup: false
        app: camp-astrolabe # app name on heroku
        on:
          repo: wojm/Astrolabe
    - if: branch = beta AND type = push AND fork = false
      branch: beta
      script: npm run build:beta
      name: Deploying app to beta environment
      before_install: npm run decrypt:gcp_private_key.json
      deploy:
        provider: gcs
        key_file: gcp_private_key.json
        bucket: beta.tech.camp
        edge: true
        cleanup: false
        acl: public-read
        local_dir: ./dist
        on:
          repo: wojm/Astrolabe
          branch: beta
```

Results in the error:
```
Install deployment dependencies
Validating required runtime version: python (>= 2.7.9)
Failed validating runtimes: python (>= 2.7.9)
failed to deploy
```

The actual job is here, but I believe it's private: https://travis-ci.com/github/wojm/Astrolabe/jobs/324750868#L527

**Comment by BanzaiMan** [comment]
Could you try using a more recent Ubuntu version?

**Comment by BanzaiMan** [comment]
The line came from https://github.com/travis-ci/dpl/commit/d67406bae933a22a7118d8431915becdcdc087fa#diff-f9a202c2ce1c78a1e644ade3fe6bfe79R14
and has persisted in some fashion since. It is not immediately clear why it should be there. (The commit appears to be a part of the initial rewrite work.)

**Pull request closed without merging**
