### PR TITLE
Alphabetise list of providers

### PR DESCRIPTION
**Pull request by ajlanghorn**
It's much easier to see if the provider you want is supported by Dpl if the
list in the README is alphabetised.

This commit also standardises a bit by adding 'AWS' in front of AWS
products, as was the existing convention with CodeDeploy and OpsWorks.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Thanks for the PR. Since I've merged a couple of new providers, this now conflicts. Could you redo it?

**Comment by ajlanghorn** [comment]
@BanzaiMan Sure; coming right up.

**Comment by BanzaiMan** [comment]
Hi, @ajlanghorn,

I went ahead and alphabetized the list. Thanks for bringing this to our attention.

Have an awesome day!

**Comment by ajlanghorn** [comment]
@BanzaiMan Sorry I didn't get to this; I was planning to, then life took over. But thank you! :)

**Pull request closed without merging**
