### PR TITLE
[NON-TESTED] change away from edge api

### PR DESCRIPTION
**Pull request by friism**
See https://devcenter.heroku.com/articles/build-and-release-using-the-api#beta-streaming-build-output

### CODE REVIEW

**Comment by friism** [comment]
Updated PR to get correct attribute per: https://devcenter.heroku.com/changelog-items/632

**Comment by friism** [comment]
@rkh It'd be great if you can take a look at this - we're looking to retire the old API.

**Comment by friism** [comment]
@rkh I fixed the test and build, I think it's failing because of a more systemic problem now.

**Comment by rkh** [comment]
Will look into it. <3 <3 <3

**Comment by rkh** [comment]
Apologies for the delay, I just got back from vacation.

**Comment by rkh** [comment]
Tried locally, works. And tests are green. :)

Gonna merge and deploy. Apologies for the delay and thank you for the contribution.

**Comment by friism** [comment]
:dancer:

**Pull request merged**
