### PR TITLE
Fix undefined local variable errors on deploy

### PR DESCRIPTION
**Pull request by clayreimann**
As see in build: https://travis-ci.org/yahoo/elide/builds/86486285

### CODE REVIEW

**Comment by clayreimann** [comment]
Hey @BanzaiMan how long till this is useable? Trying to diagnose why my deploy fails.

**Comment by BanzaiMan** [comment]
You can try it with `edge: true` until there is a release.

**Comment by clayreimann** [comment]
Cool. What's your release cadence?

**Comment by BanzaiMan** [comment]
We don't have a set schedule.

**Comment by BanzaiMan** [comment]
I've pushed 1.8.7.

**Pull request merged**
