### PR TITLE
Fix chef supermarket endpoint url

### LINKED ISSUE #303: Deploy to supermarket doesn't work
When use supermarket provider with such a config
````
deploy:
  edge: true
  provider: chef-supermarket
  user_id: express42
  client_key: ".travis/express42.pem"
  cookbook_category: Monitoring & Trending
  skip_cleanup: true
  on:
    tags: true
````

got en error. I think opscode (and now chef) change the API endpoint.

````
Uploading to http://cookbooks.opscode.com/api/v1/cookbooks
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/chef-11.18.12/lib/chef/json_compat.rb:50:in `rescue in parse': lexical error: invalid char in json text. (Chef::Exceptions::JSON::ParseError)
                                       <html>  <head><title>301 Moved 
                     (right here) ------^
````

### PR DESCRIPTION
**Pull request by evtuhovich**
Also fixes #303

### CODE REVIEW

**Comment by ikurochkin** [comment]
:+1:

**Comment by whitew1nd** [comment]
+1

**Comment by osminog** [comment]
+1

**Comment by serjs** [comment]
:+1:!

**Comment by BanzaiMan** [comment]
Please test the fix with

```yaml
deploy:
  provider: chef_supermarket
  edge: true
```

**Comment by evtuhovich** [comment]
Thanx @BanzaiMan, it works! :+1:

**Pull request merged**
