### PR TITLE
Add ExoScale Support

### PR DESCRIPTION
**Pull request by maennchen**
This Pull Request adds Support for ExoScale.

ExoScale has the same API as CloudControl except the Token Endpoint.

### CODE REVIEW

**Comment by maennchen** [comment]
I'm not sure how to do the tests. Do we need a dummy Account on ExoScale?

**Comment by BanzaiMan** [comment]
Sorry for the delay. The specs should stub responses from the service, and behave accordingly. (Some specs in `dpl` actually makes API calls to services, but this is not ideal.)

**Comment by maennchen** [comment]
I can't get the tests to work on my machine, sorry for the many commits...

**Comment by maennchen** [comment]
@BanzaiMan The tests for ExoScale pass now. If I see it correctly in the travis-ci log, it's lambda's fault the test is failing.

**Comment by BanzaiMan** [comment]
Thanks. I'll take a look tomorrow.

**Comment by BanzaiMan** [comment]
Once https://travis-ci.org/travis-ci/dpl/builds/59779337 passes, you can use this provider with `edge: true`.

**Comment by maennchen** [comment]
Thank you :-)

**Pull request merged**
