### PR TITLE
release_number, not release-number

### PR DESCRIPTION
**Pull request by neoascetic**

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
Doesn't matter, they bdoth should work.

**Comment by neoascetic** [comment]
Hmm, I didn't know. 
But mixing of underscore-separated and dash-separated options in one block looks a little bit ugly, doesn't it?

**Comment by Joshua-Anderson** [comment]
:smile: That's what happens when a bunch of people edit e same file. There are more `-` in the options block than `_` though, but I don't ccare much either way.

**Comment by neoascetic** [comment]
@Joshua-Anderson yeah, didn't notice that :D

**Pull request closed without merging**
