### PR TITLE
[RubyGem Provider] Adding support for Gemspec parameter with path

### PR DESCRIPTION
**Pull request by vishrutshah**
**Problem**:
When some ruby git repo does not have gemspec file on the root and users want to use RubyGem provider with gemspec parameter to build and publish gem, this doesn't work. Travis will build the gem but will not push anything to RubyGem and silently fails. 

_Example Repo_: [Azure/azure-sdk-for-ruby](https://github.com/Azure/azure-sdk-for-ruby/blob/master/.travis.yml)
_Current Workaround_: We change the directory before executing the deploy command so that we don't have to use gemspec with path

**Reason**:
The reason is options[:gemspec] contains the path name to the gemspec without file extension. So that 
[line 39](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/rubygems.rb#L39) will build the gem using `gem build path_to_gemspecfile.gemspec` but [line 40](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/rubygems.rb#L40) will not find the gem file using the parameter `gemspec` because it's a path name. 

**Solutions**:
In case of `options[:gemspec]` parameter provided as path to the gemspec file, it needs to extract the name from the provided path before searching the directory to upload the gem. 

Sample Travis Build: [https://travis-ci.org/vishrutshah/azure-sdk-for-ruby/builds/124303724](https://travis-ci.org/vishrutshah/azure-sdk-for-ruby/builds/124303724)

Added a unit test to verify the scenario when gemspec option has the path to the file. 

Please let me know if you want me to change anything. 

Thanks,

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Has this been tested?

**Comment by vishrutshah** [comment]
@BanzaiMan Yes i just re-tested it once again with the dummy credentials on .travis file to make sure that Rubygem builds gem with gemspec parameter with path & tries to plo. 

Travis Build: [https://travis-ci.org/vishrutshah/azure-sdk-for-ruby/builds/127342387](https://travis-ci.org/vishrutshah/azure-sdk-for-ruby/builds/127342387)
Travis File: [https://github.com/vishrutshah/azure-sdk-for-ruby/blob/master/.travis.yml](https://github.com/vishrutshah/azure-sdk-for-ruby/blob/master/.travis.yml)

**Comment by vishrutshah** [comment]
@BanzaiMan I am looking for team's feedback on this. Please let me know if we need anything more. Thanks!

**Comment by vishrutshah** [comment]
@BanzaiMan I am looking for team's feedback on this. Please let me know if we need anything more. Thanks!

**Comment by BanzaiMan** [comment]
Sorry for the long delay. If you are still interested in this feature (I hope you are!), please update the code (for dpl 1.9.x) and open a new PR.

Thanks!

**Pull request closed without merging**
