### PR TITLE
Read files in binary mode for bintray provider

### LINKED ISSUE #399: Bintray provider uploads a file partially on windows
Bintray provider reads a file to upload and put it into a body for HTTP put request.
The problem is that the provider code calls File.read(filepath) which seems to open files in text mode by default. Since Linux has no differences in open modes, it works on Linux. But it leads to uploading corrupted file (or part of the file) on windows.
The provider should always work with files as binary files.

### PR DESCRIPTION
**Pull request by Groterik**
Fixes #399.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Has this been tested?

**Comment by Groterik** [comment]
Tested under windows and linux.

**Comment by Groterik** [comment]
Ping

**Comment by BanzaiMan** [comment]
Sorry for the delay. Do you have a build log URL that shows this is working?

**Comment by Groterik** [comment]
I'm not sure what exactly you mean by "build log" but the output of `dpl --provider=bintray ...` is the same that was before the change (an example of the output here: https://ci.appveyor.com/project/Groterik/qtcreator-dlangeditor/build/1.0.9#L794). The only difference is that a binary package is uploading correctly (an example of a broken package: https://dl.bintray.com/groterik/qtcreator-dlang-tools/qtcreator-dubmanager/master/1.0/win32/).
Since the PR is not merged and released I could only test the change locally on my machine.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/dpl#writing-and-testing-a-new-deployment-provider-and-new-functionalities

**Comment by Groterik** [comment]
https://travis-ci.org/Groterik/qtcreator-dlangeditor/jobs/111363479

**Comment by Groterik** [comment]
Ping

**Comment by Groterik** [comment]
Ping, @BanzaiMan.

**Pull request merged**
