### PR TITLE
Add Provider Flynn

### PR DESCRIPTION
**Pull request by JMSwag**
https://flynn.io

### CODE REVIEW

**Comment by JMSwag** [comment]
My ruby skills are very minimal to non existent. Please let me know what needs to be done to get this merged. Please & TY!

**Comment by svenfuchs** [comment]
@JMSwag looks good. there's a syntax error (missing comma before `required` on line 14), and tests are missing. I'll merge your PR and take care of these.

Would you be able to help testing this against an actual endpoint?

**Comment by BanzaiMan** [comment]
We need a corresponding docs PR.

**Comment by svenfuchs** [comment]
@BanzaiMan thanks for the reminder! i have added that to my todo list.

**Comment by JMSwag** [comment]
@svenfuchs Yes, tonight!

Please note that when attempting to “bundle install” locally, I get the same error that’s reported in CI.

**Comment by svenfuchs** [comment]
@JMSwag nice, thank you.

the error is a result of the syntax error, should be fixed in this repo's master branch.

if you want to test this on Travis CI you can do so by adding the following to your `.travis.yml` file:

```yaml
deploy:
- provider: flynn
  edge:
     branch: master
```

**Comment by svenfuchs** [comment]
have you been able to test this @JMSwag?

**Pull request merged**
