### PR TITLE
Elastic Beanstalk provider improvements

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
Note that edf8c70a breaks backwards compatibility by removing an option. I'm thinking this is OK because dpl v2 is still not the default choice. We could keep the old option around as an (undocumented?) compatibility shim if you prefer.

### CODE REVIEW

**Comment by svenfuchs** [comment]
thanks for opening this PR, @alexjurkiewicz.  

being able to skip updating the environment sounds reasonable to me, although i don't actually have any real experience with elastic beanstalk.

so just to make sure i understand this right ... so far we require the `env` option even though people might opt out of updating the `env` entirely by specifying `only_create_app_version`, in which case having to specify `env` is useless. is that correct?

btw

> You probably also should set cleanup to false

`cleanup` is now false by default in v2, so i don't think we need to point this out.

i assume that this PR is not related to the issue you reported here, right? https://github.com/travis-ci/dpl/issues/1173

**Comment by alexjurkiewicz** [comment]
Hey Sven, your understanding of workflow is correct. We upload build and
use a non Travis system to deploy to environments.

I'll update the zip docs

**Comment by alexjurkiewicz** [comment]
I admit to being a bit lost fixing these tests. If you could take a quick look I'd appreciate it 🙏

**Comment by alexjurkiewicz** [comment]
ping

**Comment by svenfuchs** [comment]
@alexjurkiewicz sorry, i haven't been able to have a closer look at this earlier.

i have now opened a new PR here https://github.com/travis-ci/dpl/pull/1182 with your changes, plus a commit that i believe should do the right thing https://github.com/travis-ci/dpl/pull/1182

could you please review it to see if it makes sense?

**Pull request closed without merging**
