### PR TITLE
rename --body to --release_notes, add --release_notes_file (see #155)

### PR DESCRIPTION
**Pull request by svenfuchs**
Can be tested using:

```yaml
deploy:
  provider: pages
  edge:
    branch: sf-releases-release-notes
⋮
```

### CODE REVIEW

**Comment by BanzaiMan** [comment]
I think `body` is an Octokit/API-provided option that gets tied to Releases, so I am not a fan of removing this option.

**Comment by svenfuchs** [comment]
@BanzaiMan it doesn't remove it, but still keeps it as an alias (so people's deploy configs won't break)

but i'm not sure we have to stick with Octokit's nomenclature necessarily? `body` seems like a rather technical detail to me, and "release notes" is what they use in their documentation https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/releases.rb#L25 (which is where i've grabbed this name from)

i'm not set on `release_notes`, but i think it should be something that works well with a prefix `_file` ... i'd think `body_file` would be just too weird :)

**Comment by BanzaiMan** [comment]
OK. I have no other concerns.

**Comment by Midnighter** [comment]
@svenfuchs I tried to test it with the following demo repo https://github.com/Midnighter/travis-release-notes/ but my config is not recognized and doesn't trigger a job :disappointed: 

Does it only work for `provider: pages`? I thought most people in #155  wanted it for `provider: releases`.

Also doesn't help that there is no clear way to validate a configuration :/ but that's another issue.

**Comment by svenfuchs** [comment]
@Midnighter it seems your config has both a `matrix` and a `jobs` key. these are aliases, and `matrix` will take precedence, so `jobs` is silently ignored, unfortunately. i'd recommend moving `fast_finish: true` into the `jobs` section, and removing `matrix`.

> Does it only work for `provider: pages`?

whoops, no, sorry. bad copy and paste, i've fixed that. these options are available on the `releases` provider https://github.com/travis-ci/dpl/blob/master/lib/dpl/providers/releases.rb#L28

**Comment by Midnighter** [comment]
Thanks for the hint! I got the deploy to run but now the file is not found and I don't get a lot of information from the log to try and fix it.

https://travis-ci.org/Midnighter/travis-release-notes/jobs/579659390

**Comment by svenfuchs** [comment]
@Midnighter that's because the release provider expects you to specify a `file` option in your build config https://github.com/Midnighter/travis-release-notes/blob/c03b6281fc3cbdbc44a32ead08b31a6b27ae4a36/.travis.yml#L35 (see https://docs.travis-ci.com/user/deployment/releases/)

If you meant to upload all files then you can specify:

```
deploy:
  - provider: pages
     file: *
     file_glob: true
```

I have also opened https://github.com/travis-ci/dpl/pull/1093 that would switch this around a little, and make your current config behave the same. I think that would be slightly better UX, but I'm not yet sure if we want to merge that PR.

If you want to give it a try nonetheless, you can use:
```
deploy:
  - provider: pages
     edge:
       branch: sf-releases-file
```

On that branch `file` and `file_glob` would not be required any more, but default to the same behavior.

**Comment by svenfuchs** [comment]
Also curious that you are getting that noisy backtrace on your build log. That actually shouldn't be there.

**Comment by Midnighter** [comment]
Ah, thank you. I tried to create a minimal example but I'm forgetting the important bits :wink: Thanks for your help.

**Comment by Midnighter** [comment]
Works great! Thank you for the PR and your help here :heart: 

See result https://github.com/Midnighter/travis-release-notes/releases

**Comment by MarkCallow** [comment]
Does this work in dpl v1? I can't use dpl v2 dues to #1213.

**Pull request merged**
