### PR TITLE
"Bintray" Provider

### PR DESCRIPTION
**Pull request by eyalbe4**
Added "Bintray" provider.

### CODE REVIEW

**Comment by eyalbe4** [comment]
Hi,
I'm not quite sure why Github complains about the conflict.
In an attempt to fix the issue, I tried committing README.md and provider.rb again after updating them, but the warning message persists.
Since my additions to the above 2 existing files are relatively minor (most of the code is in the new bintray.rb file), can you please try and merge this?
I appreciate your help. Thanks!

**Comment by rtyler** [comment]
@eyalbe4 I'm creating a branch based off your changes to make sure they merge properly, do you mind if I submit a subsequent pull request with them?

**Comment by eyalbe4** [comment]
@rtyler , Sure, please do! Thanks for the help!

**Comment by rtyler** [comment]
@eyalbe4 I've pushed cleanups into #256 which is ready to be merged if you want to close this pull request.

**Comment by eyalbe4** [comment]
Thanks a lot for the help @rtyler !
I'm closing this one.

**Pull request closed without merging**
