### PR TITLE
Cloud Foundry V3 Push Support

### PR DESCRIPTION
**Pull request by osis**
Adds support for the new v3-push feature for zero downtime deploys.

### CODE REVIEW

**Comment by osis** [comment]
@BanzaiMan Looks like master has a broken test?

**Comment by BanzaiMan** [comment]
Is it possible to infer (from whatever source of truth) which version of the command is required/preferred? (It may also be possible to try one first, and if that fails, fall back to the other.)

Also, please test it.

**Comment by svenfuchs** [comment]
Hey @osis :wave:

We are working on releasing a new major version dpl v2. The respective branch has been merged to master, and we are planning on releasing a developer preview, as well as a blog post soon, hopefully later this week.

I have ported your work on this branch to a new PR here: https://github.com/travis-ci/dpl/pull/1043. I believe this should be equivalent to your work.

If you would like me to amend the commit in order to add your Git user name and email address please let me know. (My commit was based on your work, so I would happily pass authorship for it, but I also did not want to presume.)

It would be great if you could help us test if the issue that your change was meant to address. You can opt into using dpl v2 by adding this to your `.travis.yml` file:

```yaml
deploy:
  provider: [provider-name]
  edge:
    branch: master
⋮
```

Thank you!

**Comment by osis** [comment]
Thanks a bunch @svenfuchs! I’ll take a look.

**Comment by svenfuchs** [comment]
@osis thank you! i'll close this PR here then. feel free to reopen if needed.

**Pull request closed without merging**
