### PR TITLE
Scalingo provider

### PR DESCRIPTION
**Pull request by Zyko0**
Add of [Scalingo](https://github.com/Scalingo/) provider to dpl.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Thanks for the PR! Has this been tested?

**Comment by Zyko0** [comment]
Yes, it has been tested!
However, it uses [Scalingo cli](https://github.com/Scalingo/cli) and since the official installer place it in `/usr/bin` and asks for sudo rights, I'm downloading it through curl like other providers do. Moreover, since it is a go binary, it is a bit heavy. 
I just print the command that would download and install it, is it the correct way to do it?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the test result? If it requires `sudo`, it can't be used on containers.

**Comment by BanzaiMan** [comment]
For testing, please consult https://github.com/travis-ci/dpl/blob/master/TESTING.md

Let me know if you have problems. Thanks.

**Comment by Zyko0** [comment]
Thank you for pointing the testing part out!
Do you know if I can just tell the user to download Scalingo command-line client manually by giving him the command or do I have to download it locally like other providers do?

**Comment by BanzaiMan** [comment]
For better UX, I suggest doing this in the provider for the user.

**Comment by Zyko0** [comment]
Here is the link you asked for : https://travis-ci.org/Zyko0/sample-app

**Comment by Zyko0** [comment]
[This commit](https://github.com/travis-ci/dpl/commit/0c11b6a11c2075608790ad88fbd40c8e5ef306aa) seems to make some specs like [S3](https://github.com/travis-ci/dpl/blob/master/spec/provider/s3_spec.rb#L144) fail.

**Comment by BanzaiMan** [comment]
Sorry for the inconvenience. Could you rebase this PR?

**Comment by Zyko0** [comment]
Good to go.

**Comment by Zyko0** [comment]
Hi @BanzaiMan is there anything that I missed?

**Comment by BanzaiMan** [comment]
Sorry about the delay. Could you run the build one last time to ensure that the test works?

**Comment by Zyko0** [comment]
No problem!
Here is another build : https://travis-ci.org/Zyko0/sample-app/builds/91817885

**Comment by Zyko0** [comment]
:+1:

**Pull request merged**
