### PR TITLE
Use AWS S3 SDK V2 for Elastic Beanstalk

### PR DESCRIPTION
**Pull request by jasny**
The Elastic Beanstalk provider uses the S3 sdk to upload the new version in order to deploy it. The S3 provider uses the AWS S3 SDK V2, but Elastic Beanstalk still uses V1.

See #246 for why V2 is preferred.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Sorry about the delay. Could you update this PR and test it, please?

**Comment by jasny** [comment]
* [x] Rebased (solve conflicts)
* [ ] Tested

**Comment by jasny** [comment]
@BanzaiMan Some other library seems to need `nokogiri` as sub-dependency. By removing the dependency and version specification for Elastic Beanstalk, gem now tries to install the latest, which fails.

I have no idea what library is requiring nokogiri, making it difficult to solve. Can you please take a look?

**Comment by BanzaiMan** [comment]
@jasny Perhaps `fog-xml`. https://github.com/travis-ci/dpl/issues/561#issuecomment-270212637

**Comment by BanzaiMan** [comment]
@jasny Could you update your branch one more time?

**Comment by BanzaiMan** [comment]
@jasny The following fixes the dependency issue.

Also, has this been tested anywhere?

I'd really like to merge this and have a release soon.


```diff
From 1435302c78c4e76ac9560be9e32ee6b16ba85889 Mon Sep 17 00:00:00 2001
From: Hiro Asari <asari.ruby@gmail.com>
Date: Tue, 21 Mar 2017 10:57:14 -0400
Subject: [PATCH] Pin nokogiri to 1.6.8.1

For Ruby 1.9
---
 Gemfile | 1 +
 1 file changed, 1 insertion(+)

diff --git a/Gemfile b/Gemfile
index f464636..710d779 100644
--- a/Gemfile
+++ b/Gemfile
@@ -49,6 +49,7 @@ group :cloud_files do
   gem 'fog-google', '< 0.1.1', platforms: :mri_19
   gem 'fog-profitbricks', '< 2.0', platforms: :mri_19
   gem 'fog'
+  gem 'nokogiri', '~> 1.6.8.1'
 end

 group :releases do
--
2.2.1

```

**Comment by jasny** [comment]
@BanzaiMan Kind of.... We (LegalThings) are running our own fork of DPL, which includes this patch, but doesn't include the latest commits made upstream.

**Comment by BanzaiMan** [comment]
@jasny Could you send the build log URL to support@travis-ci.com? Do you mind fixing the specs?

**Comment by BanzaiMan** [comment]
Hi, @jasny,

I'm going to close this in favor of #620, which fixes the spec failures.

**Pull request closed without merging**
