### PR TITLE
Bump packagecloud to v1.0.8 to add Node.js package support

### PR DESCRIPTION
**Pull request by capotej**
Hi, just bumping our packagecloud library to add Node.js package support to the packagecloud provider. Similar to our [previous pull request](https://github.com/travis-ci/dpl/pull/541).

Repository: https://github.com/computology/node-test-package/blob/master/.travis.yml
Successful build: https://travis-ci.org/computology/node-test-package

Not sure if any authentication/verification is needed, but [I work for packagecloud.io](https://github.com/orgs/computology/people).

Let me know if you need me to do anything else to merge this, thanks!

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Hello, there. Is there a test deployment with this code?

**Comment by capotej** [comment]
Hi, thanks for taking a look at my PR.

I've deployed several test packages with this code to this repository: https://packagecloud.io/capotej/node-test

(See PR description for github repository and travis build)

**Comment by BanzaiMan** [comment]
Sorry for the delay. We would be reorganizing code a little bit (for the upcoming 1.9.0 release, to require Ruby 2.2), and some additional changes will be necessary.

**Comment by BanzaiMan** [comment]
We've rearranged the way dependency is specified in `dpl` provider gems. In this case, we need to change https://github.com/travis-ci/dpl/blob/b8fdf40df220882772542bb49a7ebba2df7e3081/dpl-packagecloud.gemspec#L3. I'm closing this now. Please open a new PR to affect the desired change.

Thank you!

**Comment by BanzaiMan** [comment]
I can write the update, if you'd prefer that.

**Comment by capotej** [comment]
I was actually going to push this up today, so no need, thanks for the offer though!

**Pull request closed without merging**
