### PR TITLE
Clean up after a failed `git clone'

### PR DESCRIPTION
**Pull request by native-api**
Should fix https://travis-ci.community/t/failed-to-deploy-because-of-ruby-error/1143 according to https://travis-ci.community/t/failed-to-deploy-because-of-ruby-error/1143/7

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Hello, there. Thanks for the PR. Please point to a test deploy that shows that this PR fixes the issue. Thanks.

**Comment by native-api** [comment]
Initial failed deployment: https://travis-ci.org/native-api/test_travis/builds/547026537
Successful deployment with the fix: https://travis-ci.org/native-api/test_travis/builds/547385362

**Comment by native-api** [comment]
@BanzaiMan Any status update here? Did the problem go away, or the PR is lacking or something?

**Comment by BanzaiMan** [comment]
Thanks for the ping!

**Comment by native-api** [comment]
@BanzaiMan I assumed that you would get a notification when I posted https://github.com/travis-ci/dpl/pull/1005#issuecomment-503281787 since you replied earlier and should have been automatically subscribed to the ticket.

Is that not so? Do I have to @ping you explicitly in the future as well?

**Pull request merged**
