### PR TITLE
Move TESTING into CONTRIBUTING doc

### PR DESCRIPTION
**Pull request by webknjaz**
So that it gets picked up by GitHub and shown to users when they
create an issue or submit new PR.

### CODE REVIEW

**Comment by webknjaz** [comment]
@BanzaiMan this should improve user experience and noticeability of test requirements.

**Comment by BanzaiMan** [comment]
Sounds reasonable. Could you add `[skip ci]` to the commit subject?

**Comment by webknjaz** [comment]
Sure, but you can change the merge commit title when merging anyway :)

**Comment by BanzaiMan** [comment]
Ha. I forgot about that. 😆

**Comment by BanzaiMan** [comment]
Now, Travis won't even start, and the requirement is never met. Please remove it. I am sorry for going back and forth on this.

**Comment by webknjaz** [comment]
Haha) :laughing: You can still change commit title yourself :)

**Pull request merged**
