### PR TITLE
Feature: Update Cloud Foundry provider for container-based infrastructure

### PR DESCRIPTION
**Pull request by TYsewyn**
Change the way we download, install en run the CF CLI so we can run this on the container-based infrastructure

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Hi, there. Could you fix up the specs, please?

**Comment by BanzaiMan** [comment]
I fixed up the specs.

**Comment by TYsewyn** [comment]
Sorry, I didn't had the time to fix the anynines spec.

Since the anynines provider is based on CloudFoundry, you should also change the way the cf command is executed in https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/anynines.rb.
 'cf' should be changed in './cf', that way the anynines provider can also be run on the container-based infrastructure.

**Comment by cwest** [comment]
I tested this feature with a [deployment](https://travis-ci.org/cwest/gina/builds/78823590) which was successful. My change to exercise it was https://github.com/cwest/gina/pull/6.

**Comment by BanzaiMan** [comment]
@TYsewyn No worries. It's already done.

@cwest Thanks for testing!

I'll release 1.8.2 Tuesday.

**Pull request merged**
