### PR TITLE
Integrate Atom Package Manager

### LINKED ISSUE #378: Add support for Atom Package Manager?
Would it be feasible to add support for the [Atom](https://atom.io) Package Manager? It seems to be fairly similar to Node Package Manager, in fact under the hood APM uses NPM for dependency management.

There are a lot of Atom packages using Travis for testing right now, I think it'd be awesome to use Travis to deploy new versions as well.

### PR DESCRIPTION
**Pull request by keplersj**
Fixes #378 

It's working!

### CODE REVIEW

**Comment by kepler0** [comment]
Okay... I don't know why it's failing. But it seems to me that the APM stuff is being run and passing. I still need to finish the testing, however.

**Comment by kepler0** [comment]
And I will squish the commits before this is good to merge however.

**Comment by kepler0** [comment]
@joshk @BanzaiMan Should be good to merge. I'm open to any suggestions you may have though.

**Comment by keplersj** [comment]
If someone wants to pick this back up go for it! i'm leaving my fork, and this branch, up in case anyone wants the code.

**Comment by trevordmiller** [comment]
Why wasn't this merged? I'd like to see native support for apm deploys :)

**Pull request closed without merging**
