### PR TITLE
Update default lambda runtime

### PR DESCRIPTION
**Pull request by martincostello**
Update the default lambda runtime to node.js 4.3 as ```node``` has been deprecated and [no longer works](https://travis-ci.org/martincostello/alexa-london-travel/builds/196336961#L333).

See travis-ci/docs-travis-ci-com#974.

### CODE REVIEW

**Comment by martincostello** [comment]
[Link to deprecation announcement from AWS](https://forums.aws.amazon.com/ann.jspa?annID=4142).

**Comment by martincostello** [comment]
It'd be nice if someone, y'know, even _looked_ at this PR...

**Comment by BanzaiMan** [comment]
Thanks for the ping. Do you have a test deployment?

**Comment by martincostello** [comment]
Here's some links to an old version of my Alexa skill that deploys to AWS Lambda that used `nodejs4.3` (it now uses `nodejs6.10`).

  * [Travis configuration](https://github.com/martincostello/alexa-london-travel/blob/09017450535aa64db64a506e420cf8b98b1f94fc/.travis.yml#L24)
  * [Build with deployment using that configuration](https://travis-ci.org/martincostello/alexa-london-travel/builds/255633289)

**Comment by BanzaiMan** [comment]
That is [overriding `runtime`](https://github.com/martincostello/alexa-london-travel/blob/84cfab91528a99bda09bd09107ca374be65399d0/.travis.yml#L36), right? Please have a test deployment, as described https://github.com/travis-ci/dpl/blob/master/TESTING.md

**Comment by martincostello** [comment]
Yes, I'm overriding it because the current default does not work anymore because it's deprecated, you can't deploy Lambdas at all anymore with the default settings, hence this PR.

I'll look at setting up a test deployment to validate that this feature isn't broken anymore.

**Comment by BanzaiMan** [comment]
https://docs.aws.amazon.com/sdkforruby/api/Aws/Lambda/Client.html

>   runtime: "nodejs", # required, accepts nodejs, nodejs4.3, nodejs6.10, java8, python2.7, python3.6, dotnetcore1.0, dotnetcore2.0, nodejs4.3-edge, go1.x

`nodejs` seems a reasonable default at this time.

**Pull request closed without merging**
